version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  
  pre_build:
    commands:
      - pip install cfn-lint

  build:
    commands:
      - cfn-lint deploy/master.template.yml
      - ./deploy/create-config-files.sh

artifacts:
  discard-paths: yes
  files:
    - "deploy/master.template.yml"
    - "bdc-infrastructure.*.config.json"