Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: bdc

Outputs:
  ClusterName:
    Value: !Ref Cluster
    Description: Name of the ECS Cluster for Brekke Dance Center Services
    Export:
      Name: !Sub ${AWS::StackName}:ClusterName