Description: Shared Infrastructure for Brekke Dance Center
Parameters:
  EnableServiceStopping:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Description: Whether or not to stop services an hour after development

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: bdc
      Tags:
        - Key: ENABLE_SERVICE_STOPPING
          Value: !Ref EnableServiceStopping

Outputs:
  ClusterName:
    Value: !Ref Cluster
    Description: Name of the ECS Cluster for Brekke Dance Center Services
    Export:
      Name: !Sub ${AWS::StackName}:ClusterName