Description: Shared Infrastructure for Brekke Dance Center
Parameters:
  DomainName:
    Type: String
    Description: Domain name for Brekke Dance Center
    Default: brekkedancecenter.com

Resources:
  PrimaryHostedZone:
    Type: Custom::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !ImportValue cfn-hosted-zone-resource:HostedZoneLambdaArn
      Name: !Ref DomainName
      DelegationSetId: !ImportValue cfn-dns:DelegationSetId
      HostedZoneConfig:
        Comment: The hosted zone for brekke dance center

  ClassesSslCertificate:
    Type: Custom::Certificate
    Properties:
      ServiceToken: !ImportValue cfn-certificate-resource:CertificateLambdaArn
      DomainName: !Sub classes.${DomainName}
      SubjectAlternativeNames:
        - !Sub classes.dev.${DomainName}
      ValidationType: DNS
      HostedZoneId: !Ref PrimaryHostedZone

  ClassesListenerCertificate: 
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      ListenerArn: !ImportValue cfn-gateway:HttpsListenerArn
      Certificates:
        - CertificateArn: !Ref ClassesSslCertificate
  
  ClassesDevDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref PrimaryHostedZone
      RecordSets:
        - Name: !Sub classes.dev.${DomainName}
          Type: A
          AliasTarget:
            HostedZoneId: !ImportValue cfn-gateway:LoadBalancerCanonicalHostedZoneId
            DNSName: !ImportValue cfn-gateway:LoadBalancerDnsName
        - Name: !Sub classes.dev.${DomainName}
          Type: AAAA
          AliasTarget:
            HostedZoneId: !ImportValue cfn-gateway:LoadBalancerCanonicalHostedZoneId
            DNSName: !ImportValue cfn-gateway:LoadBalancerDnsName

  ClassesProdDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref PrimaryHostedZone
      RecordSets: 
        - Name: !Sub classes.${DomainName}
          Type: A
          AliasTarget:
            HostedZoneId: !ImportValue cfn-gateway:LoadBalancerCanonicalHostedZoneId
            DNSName: !ImportValue cfn-gateway:LoadBalancerDnsName
        - Name: !Sub classes.${DomainName}
          Type: AAAA
          AliasTarget:
            HostedZoneId: !ImportValue cfn-gateway:LoadBalancerCanonicalHostedZoneId
            DNSName: !ImportValue cfn-gateway:LoadBalancerDnsName

  TxtRecords:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrimaryHostedZone
      Type: TXT
      TTL: 300
      Name: !Ref DomainName
      ResourceRecords:
        - '"v=DMARC1; p=reject; rua=mailto:dmarc@cythral.com"'
        - '"v=spf1 ip4:45.76.28.36 ip6:2001:19f0:5c01:4eb:5400:ff:fe7b:31f9 ip6:2001:19f0:5c01:4eb::1"'
        - '"google-site-verification=v9-sK-yOnPNGRrlrfNKGjCQIY5XiCOnB7nt6LCrRAOM"'